### ISSUE TITLE
boxplot_abundance paired unclear documentation

### ISSUE THREAD

**Issue by antagomir** [microbiome/microbiome#11]
I would like to be able to plot boxplot_abudance on paired fecal and biopsy samples (paired as in they are obtained from the same participant). What happens if that particular OTU occurs in fecal but does not occur in biopsy, right now it's pairing multiple samples in the biopsy group to just one sample in the fecal group (which is not the exact corresponding pair)
Can you help me interpret the plot better? I would like that each biopsy sample is paired with its corresponding fecal counterpart at 0 even if that OTU is absent in the plot.
Do multiple lines mean that there are multiple overlapping points at that same 'signal' value? Because it happens at non-zero signal values as well.

**Comment by antagomir** [comment]
In principle the lines should combine points that have the same value in the subject field. If you provide a reproducible example (data can be sent by email as well), I can have a closer look.

**Comment by manasishah86** [comment]
Hi Leo,

The problem seems to have resolved when I changed the relative abundance transformed data to raw abundance counts. Small changes in relative abundance values are hard to discern on the y-axis especially since I have a mix of samples with variable sampling depth. 

Thanks for for contributing code for this particular plot, it helped me a lot,

Best,
Manasi

**Comment by antagomir** [comment]
Hmm. Did you use log10 with the relative abundances ? That is the default, though. Anyway good to hear that the code itself was correct.
