### ISSUE TITLE
100% prevalence

### ISSUE THREAD

**Issue by inesdoesstats** [microbiome/microbiome#116]
Trying to compute a core microbiome with 100% prevalence but I never get any output ie. always get the error  'OTU abundance data must have non-zero dimensions'. I've tried aggregating at genus level and prevalence of 99% and I only get 1 taxa. Yet when I look at the abundance all samples (n=30) have an abundance value meaning it should be 100% prevalence. How come it doesn't show me the same result with 100% prevalence?

**Comment by antagomir** [comment]
Have you checked the function argument "include.lowest"? The given prevalence threshold is the boundary value that is not included by default, i.e. you are now looking at prevalences that are strictly >100% (by default include.lowest = FALSE). With include.lowest = TRUE you should get >= 100% and the issue is solved. This has to be either way, and if we would have include.lowest by default then we will have an analogous problem with prevalence > 0% which has also caused confusion in the past.
