### ISSUE TITLE
multKM transformation function

### ISSUE THREAD

**Issue by sarastickley** [microbiome/microbiome#128]
Hi all,

When following the data transformation portion of the tutorial I am facing some problems with the multKM function. I am trying to run the multKM function on the dietswap data as shown in the tutorial: x3<-multKM(transform(x, 'compositional"), label=0, dl=rep(0,ncol(x)), n.draws=10, n.knots=NULL).
I got this error: "Error in as.data.frame.default(x[[i]], optional = TRUE) : cannot coerce class ‘structure("phyloseq", package = "phyloseq")’ to a data.frame". So I converted the data to a matrix using: abundances(transform(x, "compositional")).

However I am now getting this error: **"Error in smooth.spline(x.km, y.km) : smoothing parameter value too small".** I was wondering if anyone was able to get the multKM function working for the dietswap data or had any clues as to what I should try next?

Cheers,
Sara Stickley

**Comment by antagomir** [comment]
Hi Sara - the `multKM` function is from zCompositions R pkg, rather than microbiome. This example was commented out, and I will now removed it as we did not get it working immediately. It seems to me that the problem is related to the use of multKM function, you could also try to ask support from the developers of zCompositions package. If you manage to solve the issue, it would be great to have a working example.
