### ISSUE TITLE
CLR transform

### ISSUE THREAD

**Issue by BangzhuoTongUU** [microbiome/microbiome#213]
Hi,

I am applying **transform** function (**CLR** transformation) to **Humann gene family abundance** data (so the abundance are not all integer, some are floats) which works very well. However, when I normalized the gene family abundance by the **sequencing depth** and then applied CLR to the normalized abundance, I found out the CLR transformaed value of normalized abundance and the CLR transformed value of the raw abundance are **identical**. Do you have any idea why is that? I also tried the original **vegan::decostand** function with **clr and with pesudocount as 1**, the transformed abundance of the normalized and not-normalized abundance are **not identical**. Would it be because of the pesudocount? Could you help me debug it? I could send you a copy of my data by email if you need.

Best, 

Ben

**Comment by BangzhuoTongUU** [comment]
Problem sovled

**Comment by antagomir** [comment]
The reason is that the microbiome pkg always transforms the data into compositional abundances first, then applies CLR. We should probably remove that. I have later contributed the vegan::decostand implementation, which is used in the mia R/Bioconductor package for microbiome analyses and there this issue has been solved already.

**Comment by antagomir** [comment]
Fixed in #214
