### ISSUE TITLE
Error in travis build

### ISSUE THREAD

**Issue by microsud** [microbiome/microbiome#26]
Hi- The was an error  in the 'Error in travis build' for the updates i did as suggested previously.  Could you please help me debug this.
https://travis-ci.org/microbiome/microbiome/builds/210866256

Cheers,
Sudarshan

**Comment by antagomir** [comment]
Thanks. I think it will work now although we have to see what Travis says. The problem is that there are too many tutorials integrated in the package and as a result too many packages become loaded and the NAMESPACE gets full. I should find a more permanent solution, probably by separating the tutorials from the package core. But how to best integrate this with travis automated builds etc need to think a bit. So Im leaving this issue open. You should be able to proceed now, however.
