### ISSUE TITLE
Plot regression

### ISSUE THREAD

**Issue by dheerajdhotre** [microbiome/microbiome#48]
@antagomir @microsud error in plot_regression. 
plot_regression(diversity ~ Age, meta(pseq))  this gives error 
```
Error: All select() inputs must resolve to integer column positions.
The following do not:
*  DV
```
diversity column already in pseq object in example data atlas1006. but with my data how do i add the diversity column in metadata.

This is how i have added the column in metadata file and it resolved the issue

diversity <- estimate_richness(pseq, measures = "shannon")
metadata <-  meta(pseq)
metadata$Shannon <- diversity$Shannon
p <- plot_regression(Shannon ~ Age, metadata)
print(p)

**Comment by antagomir** [comment]
Thanks !

This is not exactly an  error. The function assumes that the indicated variables (diversity, Age) are available in the data.frame (here meta(pseq)). This way the function can be generic. 

The proposed method works and we could add it to the examples. However, assigning new metadata fields to phyloseq objects is already described in the tutorial: http://microbiome.github.io/microbiome/Preprocessing.html

Although this is not linked from the diversity page so it may not be obvious.

Note that the microbiome package has been unstable as it was under heavy development. Now it starts to stabilize. In the latest version the estimate_richness function is replaced by functions "global" and "richness" but otherwise they work the same.
