### ISSUE TITLE
Tutorial: potential analysis

### ISSUE THREAD

**Issue by sijy** [microbiome/microbiome#58]
Hi, 
I was trying the potential analysis and got the following errors:

1) diversity <- exp(microbiome::diversity(pseq)$shannon)

Here, I think microbiome::diversity needs to be corrected to microbiome::diversities

2) By running res <- movpotential_ews(diversity, age), I got...

Error in maxima[[j]] : subscript out of bounds
In addition: Warning messages:
1: In movpotential_ews(diversity, age) :
  The data contains NAs, removing the associated samples from X and param input arguments.
2: In min(maxima) : no non-missing arguments to min; returning Inf
3: In max(maxima) : no non-missing arguments to max; returning -Inf

I found NAs in age and tried to run the command again after removing them, but didn't work out.

Thank you in advance!

**Comment by antagomir** [comment]
Diversity naming fixed, thanks for pointing out (was fixed already longer time ago but I overlooked this issue). The movpotential_ews is an issue for the separate earlywarnings R package and should be fixed there. This example has been moved to experimental examples since there are no guarantees of stability.
