### ISSUE TITLE
Bug? error when modifying plot_composition() plots

### ISSUE THREAD

**Issue by wolass** [microbiome/microbiome#6]
It was possible to modify the `composition_plot()` with additional ggplot2 functions.

Now whenever I would add a 
`+scale_fill_manual()`

 or any othe ggplot2 function it trows an error:

`non-numeric argument to binary operator`

**Comment by wolass** [comment]
Ok I figured you changed the  structure of the composition_plot() to return a list. It was not so clear as I am used to different behaviour from the "microbiome package". :)
So wheneve I want to access the plot I would add $plot at the end of the function.

It's fine, but:

whenever I simply call plot_composition() on phyloseq object it will not be "silent" meaning that it will produce the following message:

    $plot
    
    $data
    phyloseq-class experiment-level object
    ...

How to get rid of this?

**Comment by antagomir** [comment]
Yes this was intentional. Originally I thought that the user (me) would also like to get access to the phyloseq object used for plotting (which is potentially different from the original input version due to the transformations). As a quick hack I just returned both the plot and the phyloseq object. This is non-standard, however, and not really necessary so I decided to remove it. In the next commit the function will only return the ggplot object and nothing else, solving this issue.
