### ISSUE TITLE
Plot_composition function 

### ISSUE THREAD

**Issue by microsud** [microbiome/microbiome#60]
@antagomir the plot_composition function has changed and the arguments in tutorial no longer exists. I would prefer the previous function with options for taxonomic.level, transform in this function as colleagues at MIB found it more useful.

Cheers,
Sudarshan

**Comment by antagomir** [comment]
I can see the motivation. I realized, however, that the function is overly complex to maintain and gets easily unstable with any changes. I would propose splitting it into multiple smaller and more coherent components, for instance plot_composition_barplot, plot_composition_heatmap etc. Mappings between taxonomic level and transformations are readily available one-liners that can be applied before the function. From maintenance point of view it would be more simple to provide clear examples, rather than try to accommodate all potential (and versatile) use cases into a single function. This is commonly accepted standard programming practice. A temporary fix could be to provide the old function as a separate gist that can be used. But let me know what you think after these arguments.

**Comment by microsud** [comment]
@antagomir I can understand what you mean here. Assuming that the `transform` and `aggregate_taxa` are core functions these will not be changing i would prefer to have the older functionality. Output for seq data is a format we need to focus. Considering the option for different functions, I have started experimenting with a [sister repo](https://github.com/microsud/microbiomeutilities/wiki/microbiome_heatmap) ceated last weekend for me to play around with testing. We can think of adding this functionality after some polishing. For now, I have given the fix to MIB.

**Comment by antagomir** [comment]
Ok fine for now. But we may have to reconsider these policies when the overall project goes fwd and coherence is needed. If your function extends the old one and works then it is OK for me to include it now.

**Comment by antagomir** [comment]
Could we now start simplifying the function, and remove the extra options? I would rather keep the microbiome package simple core package. We can have further wrapper packages on top of it that can provide more complex wrappers. We could share these in the same collection of packages and ensure interoperability.

**Comment by microsud** [comment]
The current function is okay as it is. We need not play around with this. The complex aruguments have been maintained in `plot_taxa_composition` function in `microbiomeutilities` R package already.
