### ISSUE TITLE
Time Series for Individual Subjects

### ISSUE THREAD

**Issue by trobacker** [microbiome/microbiome#67]
Hello, I am trying to the run the code chunk under the Experimental Tools section of the Microbiome tutorials labeled Time Series for Individual Subjects located at the bottom of the page here: http://microbiome.github.io/microbiome/Experimental.html#interactive-interactive-plots

I get an error returned as I try to do the source command which I am unsure how to resolve:

"cannot coerce type 'closure' to vector of type 'character"

Could anyone offer some advice on this?

Thanks for any feedback!

-Thomas

**Comment by antagomir** [comment]
As it says, these are experimental and not guaranteed to work. We have scheduled polishing of time series functionality for this spring. So, this is coming but we can't immediately fix it due to time limitations. 

Meanwhile, if anyone can fix that, or contribute a new function that visualizes time series for individual subjects based on phyloseq objects then that would be welcome and acknowledged.

**Comment by antagomir** [comment]
I can't reproduce this bug with the above-mentioned page, so have to assume for now that it is fixed. Until proved otherwise.
